apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: example-gitops-app
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: example-repo
  interval: 10m
  path: ./manifests
  prune: true
  validation: client
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nats-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://nats-io.github.io/k8s/helm/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nats-release
  namespace: nats
spec:
  interval: 5m
  chart:
    spec:
      chart: nats
      sourceRef:
        kind: HelmRepository
        name: nats-repo
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 1