apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-nats
  namespace: todo
spec:
  interval: 5m
  chart:
    spec:
      chart: nats
      sourceRef:
        kind: HelmRepository
        name: nats-repo
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 1
